on:
    push:
        branches: main
    pull_request:
        branches: main

name: pkgdown

jobs:
    pkgdown:
        runs-on: ubuntu-latest
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v2
              with:
                ref: ${{ github.event.pull_request.head.ref }}
            - uses: r-lib/actions/setup-r@v2
              with:
                use-public-rspm: true
            - uses: r-lib/actions/setup-r-dependencies@v2
              with:
                extra-packages: any::pkgdown, local::.
            - name: Generate
              run: pkgdown::build_site_github_pages ()
              shell: Rscript {0}
            - name: Commit
              run: |
                git config --local user.name "$GITHUB_ACTOR"
                git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
                git add docs
                git commit -m "Automated pkgdown update" || echo "No changes to commit"
                git pull --ff-only
                git push origin
